### ISSUE TITLE
SvelteKit: The size of the build output (716034182) exceeds the max allowed size of 230686720 bytes

### ISSUE THREAD

**Issue by johnpc** [gzimbron/amplify-adapter#2]
When I attempt to use this sveltekit adapter `amplify-adapter`, I get the following deployment error in AWS Amplify:

```
2023-12-28T18:57:39.793Z [ERROR]: !!! CustomerError: The size of the build output (716034182) exceeds the max allowed size of 230686720 bytes. Please reduce the size of your build output (/codebuild/output/src1442862685/src/test-app/build/compute/default) and try again.
```

This appears to be because it includes the full `node_modules` contents in `build/compute/default` which too large to deploy.

Great project by the way!

**Comment by gzimbron** [comment]
Hi, thanks for reporting this.
I got this error too when I try to deploy a big site.

**Comment by gzimbron** [comment]
Hi @johnpc 

I'm happy to announce that this issue has been resolved in version 0.1.0. To fix this issue, you need to add the following two commands to your amplify.yml file:

```yaml
- cd build/compute/default/
- npm i --production
```

![App build specification](https://github.com/gzimbron/amplify-adapter/blob/v0.1.0/readme_assets/buildsettings_1.jpg?raw=true)

**Comment by johnpc** [comment]
Thanks!! I’ll be using it this weekend!

**Comment by rizwaniqbalrao** [comment]
still i'm having this issue. thee commands given above doesn't works. :(

**Comment by mmurraymarsdd** [comment]
Experiencing this as well.  Looks like its mostly the node_modules directory.  Could there be another way to bundle/package the files?
