### ISSUE TITLE
404 Errors on SSR pages

### ISSUE THREAD

**Issue by tristan-valar** [gzimbron/amplify-adapter#3]
Followed the video tutorial to deploy a Sveltekit app. But everything that is server rendered throws a 404 error.

From the logs I gather that the lamdas are getting deployed and executed but still throw a 404 error

![image](https://github.com/gzimbron/amplify-adapter/assets/156662389/50add6f0-9b2f-4a80-97d6-894425f63faa)

**Comment by tristan-valar** [comment]
Omg hello! thank you for replying so fast. Yes I tried this but I am still having the same issue. Maybe its a problem related to the upgrade to sveltekit 2.0?

**Comment by gzimbron** [comment]
@tristan-valar  I recently tested the deployment of sveltekit 1.2 project, using amplify-adapter `v0.1.0`, and all ok.
Then I made an `npx svelte-migrate@latest sveltekit-2` to upgrade sveltekit version to `^2.5.0`, and access was succesfully.

Could you share your dependencies please?
